package com.github.aaoferreira.rxeventbus.api;

import lombok.Value;

import java.util.UUID;

/** Event encapsulation class */
@Value
public class Event<T> {

    private final String correlationId;
    private final T value;

    private Event(final String correlationId, final T value) {
        this.correlationId = correlationId;
        this.value = value;
    }

    /** Creates a new {@link Event} with the correlationId and value passed
     *
     * @param correlationId event correlation id
     * @param value event value
     */
    public static <T> Event<T> of(final String correlationId, final T value) {
        return new Event<>(correlationId, value);
    }

    /** Creates a new {@link Event} with a random correlationId, generated by {@link UUID#randomUUID()}
     *
     * @param value event value
     */
    public static <T> Event<T> of(final T value) {
        return new Event<>(UUID.randomUUID().toString(), value);
    }
}
